name: JS

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read
  actions: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    name: Sync fork and Run build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup PSE
        uses: invisirisk/pse-action@dev-test
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_L_STAGE }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
         node-version: "22.11.0"

      jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"

      # Install global tools (Angular CLI, Yarn, Gulp CLI)
      - name: Install global tools
        run: |
          npm install -g @angular/cli
          npm install -g yarn
          npm install -g gulp-cli

      # Install dependencies in "angular" folder
      - name: Install dependencies
        working-directory: angular
        run: yarn install

      # Run custom script (must exist in package.json scripts)
      - name: Run dynamic bundles
        working-directory: angular
        run: npm run create-dynamic-bundles

      # Run gulp build using local gulp
      - name: Run gulp build
        working-directory: angular
        run: npx gulp build

      # Angular build
      - name: Angular build
        working-directory: angular
        run: ng build #--configuration ${{ vars.ENV }} --build-optimizer --output-path=dist

      # Copy web.config
      - name: Copy web.config
        working-directory: angular
        run: cp ./web.config ./dist/web.config

        
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@dev-test
        with:
          cleanup: "true"

  gather_analytics:
   runs-on: ubuntu-latest
   name: Gather Analytics
   needs: sync-and-build
   if: always()
   steps:
   - name: Gather Status
     uses: invisirisk/pse-action@dev-test
     with:
      api_url: "https://app.stage.invisirisk.com"
      app_token: ${{ secrets.IR_API_KEY_L_STAGE }}
      send_job_status: "true"
      debug: "true"
