name: Build JS Package For Secrets (STAGE)

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  js-application-build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@dev-test
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.VB_API_KEY_STAGE }}
          
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
         node-version: "22.11.0"

      - name: install dependencies
        run: npm install
        
     # - name: Make cURL request for checksum test
      #  run: curl https://package-registry.free.beeceptor.com/packages
        
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@dev-test
        with:
          cleanup: "true"
